# Generated by Django 3.0.3 on 2020-04-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200418_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='acopio',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha Creación del Acopio'),
        ),
        migrations.AddField(
            model_name='jornal',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha Creación del Jornal'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha Creación del Recurso'),
        ),
        migrations.AddField(
            model_name='rol',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha Creación del Rol'),
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha Creación de la Venta'),
        ),
    ]
