# Generated by Django 3.0.3 on 2020-04-21 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200421_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jornal',
            old_name='Persona_id',
            new_name='idenPer',
        ),
    ]
