# Generated by Django 3.0.3 on 2020-06-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200423_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='comproVenta',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
