# Generated by Django 3.0.3 on 2020-06-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200609_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='comprobante',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
