# Generated by Django 3.0.3 on 2020-06-15 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200609_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornal',
            name='nomJornal',
        ),
    ]
